version: 0.0.{build}
pull_requests:
  do_not_increment_build_number: true
max_jobs: 1
image: Visual Studio 2015
clone_folder: C:\sqlexpress\

environment:
    #MSSQL Credentials
    MSSQL_LOGIN: sa
    MSSQL_PASS: Password12!
    
    matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      MSSQL: SQL2017
      DB_INSTANCE: (local)\SQL2017
      TARGET_DB: master
      
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      MSSQL: SQL2016
      DB_INSTANCE: (local)\SQL2016
      TARGET_DB: master
      
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      MSSQL: SQL2014
      DB_INSTANCE: (local)\SQL2014
      TARGET_DB: master
      
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      MSSQL: SQL2012SP1
      DB_INSTANCE: (local)\SQL2012SP1
      TARGET_DB: master
      
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      MSSQL: SQL2008R2SP2
      DB_INSTANCE: (local)\SQL2008R2SP2
      TARGET_DB: master

services:

build_script:
- echo Starting SQL Server
- ps: >-

    $SQLInstance = $env:MSSQL;
    Start-Service "MSSQL`$$SQLInstance";
    
- cmd: >-

    sqlcmd -S %DB_INSTANCE% -U %MSSQL_LOGIN% -P %MSSQL_PASS% -i "C:\sqlexpress\sp_SizeOptiMiser.sql" -d %TARGET_DB% -b

test_script:
- echo Testing on %MSSQL%
- cmd: >-

    sqlcmd -S %DB_INSTANCE% -U %MSSQL_LOGIN% -P %MSSQL_PASS% -Q "exec sp_sizeoptimiser" -d %TARGET_DB% -b

deploy: off