version: 0.0.{build}

pull_requests:
  do_not_increment_build_number: true
  
max_jobs: 1

clone_folder: C:\sqlexpress\

environment:
    #MSSQL Credentials
    MSSQL_LOGIN: sa
    MSSQL_PASS: Password12!
    
    #Test Files
    CREATESCRIPT1: sp_sizeoptimiser.sql
    CREATESCRIPT2: sp_helpme.sql
    CREATESCRIPT3: sp_doc.sql
    TSQLTSETCLR:  tests\tSQLt\SetClrEnabled.sql
    TSQLTCREATEDB: tests\tSQLt\CreateDatabase.sql
    TSQLTINSTALL: tests\tSQLt\tSQLt.class.sql
    TSQLTBUILD: tests\build_tsqlt_tests.sql
    TSQLTTEST: tests\run_tSQLt_tests.sql
    
    #Build Constants
    TARGET_DB: tSQLt
    
    matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      MSSQL: SQL2017
      DB_INSTANCE: (local)\SQL2017
      
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      MSSQL: SQL2016
      DB_INSTANCE: (local)\SQL2016
      
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      MSSQL: SQL2014
      DB_INSTANCE: (local)\SQL2014
      
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      MSSQL: SQL2012SP1
      DB_INSTANCE: (local)\SQL2012SP1
      
   # - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
   #   MSSQL: SQL2008R2SP2
   #   DB_INSTANCE: (local)\SQL2008R2SP2

build_script:
- echo Starting SQL Server
- ps: >-

    $SQLInstance = $env:MSSQL;
    Start-Service "MSSQL`$$SQLInstance";

- echo Installing SqlServer PS Module
- ps: Install-Module SqlServer -Force -AllowClobber
   
- echo Setting up tSQLt
- cmd: >-

    SET SCRIPT=%CLONE_FOLDER%%TSQLTSETCLR%
    
    sqlcmd -S %DB_INSTANCE% -U %MSSQL_LOGIN% -P %MSSQL_PASS% -i %SCRIPT% -d master -b
    
    SET SCRIPT=%CLONE_FOLDER%%TSQLTCREATEDB%
    
    sqlcmd -S %DB_INSTANCE% -U %MSSQL_LOGIN% -P %MSSQL_PASS% -i %SCRIPT% -d master -b
    
    SET SCRIPT=%CLONE_FOLDER%%TSQLTINSTALL%
    
    sqlcmd -S %DB_INSTANCE% -U %MSSQL_LOGIN% -P %MSSQL_PASS% -i %SCRIPT% -d %TARGET_DB% -b

- echo Installing ExpressSQL Scripts
- ps: >-

    foreach ($filename in get-childitem -path $env:clone_folder -filter "*.sql")
    {
    invoke-sqlcmd –ServerInstance $env:DB_INSTANCE -Database $env:TARGET_DB -InputFile $filename.fullname -Username $env:MSSQL_LOGIN -Password $env:MSSQL_PASS
    Write-Output "Installing " + $filename
    }

- echo Building tSQLt Tests
- cmd: >-
    SET SCRIPT=%CLONE_FOLDER%%TSQLTBUILD%

    sqlcmd -S %DB_INSTANCE% -U %MSSQL_LOGIN% -P %MSSQL_PASS% -i %SCRIPT% -d %TARGET_DB% -b


test_script:
- echo Running unit tests
- cmd: >-

    SET SCRIPT=%CLONE_FOLDER%%TSQLTTEST%

    sqlcmd -S %DB_INSTANCE% -U %MSSQL_LOGIN% -P %MSSQL_PASS% -i %SCRIPT% -d %TARGET_DB% -b


deploy: off
