on: [push]

jobs:
  tsqllint_lint_job:
    runs-on: ubuntu-latest
    name: TSQLLint
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Lint action step
        uses: ./.github/actions/tsqllint-action
        id: Lint
        with:
          file-dir-1: '*.sql'
          file-dir-2: '*.sql'
          config: './appveyor/tsqllint/.tsqllintrc_150'